### ISSUE TITLE
Is there any pre-trained model available? 

### ISSUE THREAD

**Issue by MoyanZitto** [sungheonpark/music_source_sepearation_SH_net#1]
Is there any pre-trained model available? I am quite interested in your work. It would be better if I can extract vocal/background music use your pre-trained model and see how it sounds like.

**Comment by sungheonpark** [comment]
Hi, 
I added the links for the checkpoint files which reproduces the results in the paper.
I will also upload some sample results using the model soon. Thanks.

**Comment by ASHA-KOTERU** [comment]
Hello,
The link to the checkpoints is not working,can you please look in to it
