### ISSUE TITLE
Badcase report

### ISSUE THREAD

**Issue by MoyanZitto** [sungheonpark/music_source_sepearation_SH_net#2]
Hi, it turns out the model incorrectly recognize some instrument parts in the following two music clips.

jinlichao.wav: 15s-32s
laonanhai.wav: 2min48s-3min16s

see here: https://share.weiyun.com/5BDvTi4

Basically I don't think this is acceptable.  How can we fix this? By just adding training samples?

**Comment by sungheonpark** [comment]
Hi,
The pre-trained model is intended for reproducing the results in the paper.
You may improve the performance by adding more training samples, training different models, etc.
