### ISSUE TITLE
Training set question

### ISSUE THREAD

**Issue by lvaleriu** [sungheonpark/music_source_sepearation_SH_net#3]
Hello. I have a small question about this line of code in the train_mir_1k and eval_mir_1k scripts:
"if f.startswith("abjones") or f.startswith("amy"):"

Is there any reason (except training on a smaller subset) to filter data?

**Comment by sungheonpark** [comment]
Hi, sorry for the late response.
As stated in the paper, we followed the separation scheme of previous works [6,37] to compare the performance with them.
